import fs from 'fs';
let content = fs.readFileSync('lib/recommend.ts', 'utf8');
content = content.replace('const candidateCards = cards', `
  const c = cards.find(c=>c.id==="kotak-pvr-inox")!;
  console.log("F1:", !shouldHideCardFromGenericRanking(c, input, intent));
  const minFee = input.minAnnualFee ?? 0;
  console.log("F2:", (effectiveMaxAnnualFee !== undefined && c.annualFee > effectiveMaxAnnualFee) ? false : (c.annualFee >= minFee));
  console.log("F3:", (effectiveMaxAnnualFee === undefined || hasExplicitAnnualFeeLanguage(input.query)) ? true : (c.joiningFee >= minFee && c.joiningFee <= effectiveMaxAnnualFee));
  console.log("F4:", wantsLifetimeFree ? (c.annualFee === 0 && c.joiningFee === 0 && !requiresRelationshipAccess(c)) : true);
  console.log("F5:", wantsInternationalLounge ? internationalLoungeScore(c) > 0 : wantsLounge ? loungeScore(c) > 0 || hasGuestLoungeAccess(c) : true);
  console.log("F6:", intent.wantsGuestLounge ? hasGuestLoungeAccess(c) : true);
  console.log("F7:", restrictToIssuer ? normalizeIssuer(c.issuer) === normalizeIssuer(intent.issuers[0]) : true);
  console.log("F8:", restrictToUpiCards ? hasUpiCardSignal(c) : true);
  console.log("F9:", restrictToLowForexCards ? c.forexMarkup <= maxForexMarkupForForexQueries : true);
  console.log("F10:", restrictToZeroForexCards ? c.forexMarkup === 0 : true);
  console.log("F11:", restrictToTravelCards ? qualifiesAsTravelCard(c) : true);
  console.log("F12:", restrictToRedemptionBuckets ? intent.redemptionBuckets.some((bucket) => cardMatchesRedemptionBucket(c, bucket)) : true);
  console.log("F13:", networkFilters.length ? networkFilters.some((network) => cardMatchesNetworkFilter(c, network)) : true);
  console.log("F14:", restrictToFuelCards ? hasFuelCardSignal(c) : true);
  console.log("F15:", restrictToCashbackCards ? cardEarnsCashback(c) : true);
  console.log("F16:", restrictToSegments ? restrictToSegments.some((segment) => cardMatchesSegment(c, segment)) : true);
  console.log("F17:", categoryFocus ? cardMatchesCategoryFocus(c, categoryFocus) : true);
  console.log("F18:", focusedCategory ? (c.bestFor?.includes(focusedCategory) || netCategoryReward(c, focusedCategory, categoryFocusMonthlySpend[focusedCategory] ?? 8000, includeSmartbuyLikeRewards) > 0) : true);
  const candidateCards = cards`);
fs.writeFileSync('lib/recommend.ts', content);
