"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = ReviewInboxPage;
const jsx_runtime_1 = require("react/jsx-runtime");
const telegram_inbox_1 = require("@/lib/telegram-inbox");
function formatDateTime(value) {
    if (!value)
        return "Never";
    return new Intl.DateTimeFormat("en-IN", {
        dateStyle: "medium",
        timeStyle: "short"
    }).format(new Date(value));
}
async function ReviewInboxPage() {
    const [entries, state] = await Promise.all([(0, telegram_inbox_1.readTelegramInbox)(), (0, telegram_inbox_1.readTelegramInboxState)()]);
    const entriesWithUrls = entries.filter((entry) => entry.urls.length > 0);
    return ((0, jsx_runtime_1.jsxs)("section", { className: "section", children: [(0, jsx_runtime_1.jsxs)("div", { className: "page-title", children: [(0, jsx_runtime_1.jsx)("h1", { children: "Telegram Inbox" }), (0, jsx_runtime_1.jsx)("p", { children: "Review Telegram links before turning them into latest updates, tips, or card database tasks." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "panel review-summary", style: { margin: "18px 0" }, children: [(0, jsx_runtime_1.jsxs)("div", { className: "stat", children: [(0, jsx_runtime_1.jsx)("strong", { children: entries.length }), (0, jsx_runtime_1.jsx)("span", { children: "Total synced messages" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "stat", children: [(0, jsx_runtime_1.jsx)("strong", { children: entriesWithUrls.length }), (0, jsx_runtime_1.jsx)("span", { children: "Messages containing URLs" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "stat", children: [(0, jsx_runtime_1.jsx)("strong", { children: formatDateTime(state.syncedAt) }), (0, jsx_runtime_1.jsx)("span", { children: "Last poll" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "stat", children: [(0, jsx_runtime_1.jsx)("strong", { children: state.lastUpdateId || 0 }), (0, jsx_runtime_1.jsx)("span", { children: "Latest Telegram update ID" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "notice", style: { marginBottom: 18 }, children: ["Flow: put ", (0, jsx_runtime_1.jsx)("code", { children: "TELEGRAM_BOT_TOKEN" }), " and ", (0, jsx_runtime_1.jsx)("code", { children: "TELEGRAM_CHAT_ID" }), " in ", (0, jsx_runtime_1.jsx)("code", { children: ".env.local" }), ", run", " ", (0, jsx_runtime_1.jsx)("code", { children: "npm run fetch:telegram-inbox" }), ", then review messages here. Nothing from Telegram should go directly into card data without your manual approval."] }), entries.length === 0 ? ((0, jsx_runtime_1.jsx)("div", { className: "notice", children: "No Telegram messages have been synced yet." })) : ((0, jsx_runtime_1.jsx)("div", { className: "review-list", children: entries.map((entry) => {
                    var _a, _b;
                    return ((0, jsx_runtime_1.jsxs)("article", { className: "panel review-item", children: [(0, jsx_runtime_1.jsxs)("div", { className: "review-item-head", children: [(0, jsx_runtime_1.jsx)("strong", { children: (_a = entry.urls[0]) !== null && _a !== void 0 ? _a : entry.text.slice(0, 80) }), (0, jsx_runtime_1.jsx)("span", { className: "badge", children: formatDateTime(entry.receivedAt) })] }), (0, jsx_runtime_1.jsxs)("div", { className: "meta", children: [(0, jsx_runtime_1.jsxs)("span", { children: ["Decision: ", entry.reviewDecision] }), (0, jsx_runtime_1.jsxs)("span", { children: ["Sender: ", entry.senderUsername ? `@${entry.senderUsername}` : (_b = entry.senderId) !== null && _b !== void 0 ? _b : "unknown"] }), (0, jsx_runtime_1.jsxs)("span", { children: [entry.urls.length, " URL", entry.urls.length === 1 ? "" : "s"] })] }), entry.note ? (0, jsx_runtime_1.jsx)("p", { className: "muted", children: entry.note }) : null, entry.urls.length > 0 ? ((0, jsx_runtime_1.jsxs)("div", { className: "review-block", children: [(0, jsx_runtime_1.jsx)("strong", { children: "URLs" }), (0, jsx_runtime_1.jsx)("div", { className: "review-actions", children: entry.urls.map((url) => ((0, jsx_runtime_1.jsx)("a", { className: "button secondary", href: url, rel: "nofollow", target: "_blank", children: "Open link" }, url))) })] })) : ((0, jsx_runtime_1.jsxs)("div", { className: "review-block", children: [(0, jsx_runtime_1.jsx)("strong", { children: "Message" }), (0, jsx_runtime_1.jsx)("p", { className: "muted", children: entry.text })] })), (0, jsx_runtime_1.jsxs)("div", { className: "review-actions", children: [(0, jsx_runtime_1.jsx)("span", { className: "badge", children: entry.reviewed ? "Reviewed" : "Needs review" }), (0, jsx_runtime_1.jsx)("span", { className: "badge", children: "Next step: classify manually" })] })] }, entry.updateId));
                }) }))] }));
}
